### ISSUE TITLE
Cannot serialize uri? validation failure

### ISSUE THREAD

**Issue by mithrandi** [fusionapp/clj-documint#80]
For example:

```
mithrandi@lorien ~> curl --data-binary '{"action": "concat", "parameters": {"inputs": ["aoeu"]}}' -H 'content-type: application/json' http://localhost:3000/sessions/…/perform
{"causes":[{"type":"unhandled-exception","reason":"java.lang.Exception: Don't know how to write JSON of class schema.utils.ValidationError","description":null}]}
```

**Comment by jonathanj** [comment]
Turns out this is because the validation error data from `schema.core/validate` includes things like functions (`uri?` for example), etc. that the builtin Liberator json serializer doesn't do anything with. Probably best to string-ify the validation failure reason.
